### ISSUE TITLE
Any content coming soon?

### ISSUE THREAD

**Issue by vkosnar** [hhirsch/insect-farm-dark-beetle#1]
Hey,
I noticed your issue over at TinyFarms/OpenBugFarm and wondered whether you are still running this project and if we can expect any new content. I'm personally planning to start my first batch of mealworms during the summer and having a guide created in Europe would be most helpful.
Thanks for your time and good luck with your project.

**Comment by hhirsch** [comment]
@vkosnar Yes. My farms are still running strong. I think that instead of wood chips the big tough kind of oatmeals could be used, too. I will give this a slight update and change it to markdown. What kind of content are you looking for. If you have specific questions I am looking forward to answering them.

**Comment by vkosnar** [comment]
@hhirsch Thanks for your enthusiasm, but currently I don't even know what I don't know. The biggest problem that I can think of right now is finding a source for the first batch. Did you get your frist worms from a pet store? Or are there any sources in Central Europe which are better for human consumption?

**Comment by hhirsch** [comment]
@vkosnar I got the first batch from the pet store. I don't think I ate individuals from the first generation.

**Comment by vkosnar** [comment]
@hhirsch OK I'm going to get them sometime soon. I hope to see some new stuff from you, too. Cheers

**Comment by hhirsch** [comment]
@vkosnar Already added the stuff we talked about and converted to markdown. I'll add a chat in a minute so we can talk there.
